<!DOCTYPE html>
<html>
<head>
<title>Taco Loco</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />

<link rel="shortcut icon" href="/icon.png">
<link rel="apple-touch-icon" href="/icon.png" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

<meta property="og:image" content="/icon.png">
<meta property="og:title" content="Taco Loco">
<meta property="og:url" content="http://tacolo.co">
<meta property="og:site_name" content="Taco Loco">


<link href="/style.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Rye" rel="stylesheet" type="text/css">

</head>
<body>
<center>
<div class="content">

	<div class="logo">
		<h1>
			<a href="/">Taco Loco</a>
		</h1>
	</div>

	<div class="footer">
		<a href="https://github.com/arzynik/tacoloco">Taco Loco</a> is an open source project created by <a href="http://devin.la/" target="_blank">Devin Smith</a>, and built with <a href="http://tipsy.la/" target="_blank">Tipsy</a>.
		<br><br>
	</div>
</div>
</center>

</body>
</html>